from menu import traversals
import time, sys
from graphviz import Digraph # <- importing "Digraph" to replace the logic of displaying nodes in the terminal

class Visualizer:

    def __init__(self, bst):
        self.bst = bst # Stores the received tree so that all methods can access it
    
    def _write(self, text, delay=0.04):
        """ Writes node by node dynamically """

        for char in str(text):
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(delay)

    def _build_graph(self, traversal=None):
        """ Builds the tree graph using Graphviz """

        graph = Digraph(
            format='png', # Defines the image format generated by Graphviz
            graph_attr={
                'rankdir': 'TB', # <- Defines the tree direction: Top -> Bottom
                'nodesep': '0.6', # <- Defines the horizontal distance between nodes
                'ranksep': '0.8', # <- Defines the vertical distance between levels
                'margin': '0.2' # <- Defines the margin around the graph
            },
            node_attr={
                'shape': 'circle', # <- Defines the node shape
                'fontname': 'Arial',
                'fontsize': '14',
                'style': 'filled', # <- Allows the node to have a background
                'fillcolor': 'white', # <- Defines the default node color
                'color': 'black' # <- Defines the node border color
            },
            edge_attr={
                'color': 'black', # <- Defines the color of the connections
                'arrowsize': '0.7' # <- Defines the size of the arrows
            }
        )

        if self.bst.root is None:
            return graph

        # Creates the traversal order dictionary when a traversal was requested
        order = {}

        if traversal:
            for index, value in enumerate(traversal, start=1):
                order[value] = index

        def add_nodes(node):
            """ Adds the current node and its children to the graph """

            if node is None:
                return

            # Creates a unique identifier for the Graphviz node
            node_id = str(id(node))
            # Defines the value displayed inside the node
            label = str(node.data)

            if node.data in order: # <- Shows the traversal position below the value
                label = f'{node.data}\\N°{order[node.data]}' 

            graph.node(
                node_id,
                label=label
            )

            if node.left: # <- Creates the identifier of the left child
                left_id = str(id(node.left))

                graph.node(
                    left_id,
                    label=str(node.left.data)
                )

                graph.edge(
                    node_id,
                    left_id
                )

                add_nodes(node.left)

            if node.right: # <- Same logic as the conditional above, but for the right side
                right_id = str(id(node.right))

                graph.node(
                    right_id,
                    label=str(node.right.data)
                )

                graph.edge(
                    node_id,
                    right_id
                )

                add_nodes(node.right)

        add_nodes(self.bst.root)

        return graph

    def _display_graph(self, filename='bst'):
        """ Generates the tree visualization using Graphviz """

        if self.bst.root is None:
            self._write('\n[Empty tree]\n')
            return

        graph = self._build_graph()

        # Generates the image and removes the temporary .dot file
        graph.render(
            filename=filename,
            cleanup=True,
            view=True
        )

    # Traversals below will use the logic developed previously and
    # elaborate their own displays according to their respective characteristic:
    def _symmetric(self, node):
        """ Symmetric traversal: left -> root -> right """

        if node:
            yield from self._symmetric(node.left)
            yield node.data
            yield from self._symmetric(node.right)

    def _preorder(self, node):
        """ Pre-order traversal: root -> left -> right """

        if node:
            yield node.data
            yield from self._preorder(node.left)
            yield from self._preorder(node.right)

    def _postorder(self, node):
        """ Post-order traversal: left -> right -> root """

        if node:
            yield from self._postorder(node.left)
            yield from self._postorder(node.right)
            yield node.data
            
    def _levelorder(self):
        """ Level-order traversal: top to bottom and left to right """

        if self.bst.root is None:
            return

        # Creates a queue starting from the root
        queue = [self.bst.root]

        while queue:
    
            node = queue.pop(0)

            yield node.data

            if node.left:
                queue.append(node.left)

            if node.right:
                queue.append(node.right)

    # Displaying
    def _display_traversal(self, title, values, filename):
        """ Displays the tree using Graphviz and shows the selected traversal """

        if self.bst.root is None:
            self._write('\n[Empty tree]\n')
            return

        # Converts the generator into a list so that the traversal
        # can be used both for the graph and for the terminal
        values = list(values)

        self._write(f'\n{title}\n')
        self._write('=' * len(title) + '\n')

        graph = self._build_graph(values) # <- Creates the Graphviz graph using the selected traversal

        # Generates the image and opens it automatically
        graph.render(
            filename=filename,
            cleanup=True,
            view=True
        )

        # Displays each value with a small animation
        for value in values:
            self._write(f'{value} ', 0.04)
            time.sleep(0.2)

        self._write('\n')
        self._write('=' * len(title) + '\n')

    

def wich_traversal(bst):
    """ Function that will dynamically display each traversal 
    of its respective property in the terminal to the 
    user according to a return from "traversals """

    visualizer = Visualizer(bst)

    match traversals():
        case 1:
            visualizer.display_tree()
        case 2:
            visualizer.display_symmetric()
        case 3:
            visualizer.display_postorder()
        case 4:
            visualizer.display_level()
        case 5:
            visualizer.display_preorder()

